source 'https://rubygems.org'
ruby '3.0.2'
gem 'activemodel'
gem 'activerecord', '~> 7.0'
gem 'activesupport'
gem 'json'
gem 'logger'
gem 'pg' # PostgreSQL adapter
gem 'rake'
gem 'rspec'
gem 'rubocop'
