version: "3.8"

services:
  web:
    container_name: dhis2-test-web
    image: dhis2
    build: 
      context: ../../dhis2/dhis2-setup/local
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:9080:8080 # DHIS2
    volumes:
      - ./docker/dhis.conf:/opt/dhis2/dhis.conf
      - ./docker/log4j2.xml:/opt/dhis2/log4j2.xml
      - ./docker/server.xml:/home/dhis/tomcat-dhis/conf/server.xml
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: dhis2-test-db
    image: postgis/postgis:14-3.4
    ports:
      - 127.0.0.1:7432:5432
    volumes:
      - db-dump:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/db-dump.sql
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password # needed by psql in healthcheck
    healthcheck:
      test: ["CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null"]
      start_period: 120s
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  db-dump:
